services:
  - type: static
    name: virtual-lab-frontend
    buildCommand: null
    publishPath: public
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html